### PR TITLE
New Status Bar Tab

### PR DESCRIPTION
**Pull request by Abawell**
I've made several decisions that you may not like. Just let me know and I'll go back.
- I've grouped everything related to the status bar under the same tab called "Status Bar". Time, Battery and Network.
- I limited the width of the controls. Full width controls are good for iPhone, not for macOS. If that's okay with you, I will limite the width of the others (only the necessary ones).
- I moved "Open URL" from the Applications tab to the System tab because you don't have to select an application to open a url. I planed to add more commands in Applications, like launch the selected app with parameters.

Capture d’écran 2020-07-08 à 17 27 37

### CODE REVIEW

**Comment by Abawell** [comment]
I can propose this too
image

I've tried to align all the controls horizontally, but I can't. Maybe you have a solution.

**Comment by twostraws** [comment]
Hello! Thank you for contributing – it's great to have more folks on board! These screens have already been redesigned a few times, and I don't particularly want to keep moving between designs. I'm definitely not excited about the current design, but leaving all that space looks equally odd and I can't really think of an Apple app that has a better implementation when dealing with this many controls 🤔

Perhaps we could turn back to design once we have many other features implemented? I know folks really would love to see a menu bar icon with shortcuts, or system-wide shortcut keys to trigger common events, or support for video recording, etc.

**Comment by Abawell** [comment]
I understand

**Comment by Abawell** [comment]
What about to regroup time, battery and network under a single tab ?

**Comment by twostraws** [comment]
I can totally understand why these tabs could be adjusted in any number of ways, but again I think for now let's just leave them alone – we can revisit once the actual available features have increased and we need to rethink the layout to accommodate them. Is that okay?

**Comment by Abawell** [comment]
Sure

**Pull request closed without merging**
