### PR TITLE
Use Combine for loading information

### LINKED ISSUE #8: Show iOS version for simulator device
In the list of simulators, there's multiple devices of the same model though no distinction about which version of iOS the device is relating to.

### PR DESCRIPTION
**Pull request by davedelong**
The code in `SimulatorsController` to load up the various pieces of information was quickly getting hairy with lots of sequential callbacks.

The big change in this PR is to provide a Combine wrapper around certain SimCtl commands (with the eventual goal of moving the others to use it as well). This makes the `SimulatorsController` logic _much_ simpler.

This also adds loading up Runtime information via `simctl list runtimes -j` and using that to supplement the existing runtime information parsed from the runtime identifier.

The OS version is now shown as a sub-text on the ControlView, as opposed to being part of the name. (Fixes #8)
Screen Shot 2020-02-13 at 12 59 08 PM

### CODE REVIEW

**Comment by twostraws** [comment]
You and I have very similar sidebars – I'm wondering whether folks who have more complex configurations (e.g. iPhone X on iOS 12 and iOS 13) will find it, but at the same time my gut feeling is that having version info as a subtitle below each row would be very cluttered.

**Comment by veb** [comment]
I do like the:
> The OS version is now shown as a sub-text on the ControlView, as opposed to being part of the name. 

Would be very handy.

My side bar is pretty simple though:
image

**Comment by davedelong** [comment]
This is also the sort of thing that would be trivial to put in a Preferences window

**Comment by twostraws** [comment]
We also have stacks of room in the menu bar; it's mostly default stuff right now.

**Pull request merged**
