### PR TITLE
Added camera permission reset

### LINKED ISSUE #139: Camera permission reset missing
The "App" tab allows resetting a bunch of permissions but camera permission is oddly missing (i tried a few others to see if it would affect the camera permission but didn't see an effect).

It would be awesome if camera permission resetting would be added.

Screen Shot 2021-08-27 at 10 38 03

### PR DESCRIPTION
**Pull request by scarlac**
Fixed #139

### CODE REVIEW

**Comment by twostraws** [comment]
This is odd – I don't see "camera" listed as one of the simctl permissions. Can you clarify what's going on?

**Comment by scarlac** [comment]
I never checked simctl. I just added this code to add resetting of the camera access permission which works as intended.

**Comment by twostraws** [comment]
Russ Bishop from the Simulator team at Apple [has verified this behavior is correct](https://twitter.com/xenadu02/status/1436888383129718787?s=20), so I'll merge it now. Thank you!

**Comment by scarlac** [comment]
Thanks @twostraws

**Pull request merged**
