### PR TITLE
Map view to set current user location

### PR DESCRIPTION
**Pull request by stefanomondino**
I took the liberty to add a "Map" tab with a map view
By long-pressing the map view, you set a pin.
By pressing a button, the position in the map is set to current user location in simulator.
Let me know what you think, the wrapper around MKMapView is maybe a little bit naive.

### CODE REVIEW

**Comment by stefanomondino** [comment]
image

**Comment by twostraws** [comment]
That looks beautiful – great job! Is this functionality documented by Apple somewhere? If not, it might be unsupported, which could be problematic in the future.

**Comment by stefanomondino** [comment]
Apparently not - I found it here https://github.com/lyft/set-simulator-location. 
Folks at Lyft did the reverse-engineering and found out that locations are handled through notification center. 

Might be worth pointing out that being this a notification from MacOS NotificationCenter, the worst that could happen might be that nothing could happen when the button is pressed, but this shouldn't lead to crashes. My 2 cents: I'd rather have the feature today and take the risk of seeing it broken someday rather than not having it at all. The critical piece of code is less than 10 lines of simple code.

**Comment by twostraws** [comment]
Yes, I agree: if we find that the feature disappears in the future we can just remove it. Thank you!

**Comment by twostraws** [comment]
I've filed FB7577924 asking for a supported equivalent of this. Until then, let's go for it!

**Pull request merged**
