### PR TITLE
Build the UI as a sidebar

### PR DESCRIPTION
**Pull request by davedelong**
Screen Shot 2020-02-12 at 12 53 37 PM

### CODE REVIEW

**Comment by twostraws** [comment]
Excellent work – thank you! I'm wondering whether the sidebar will be annoying for most of us, because the default sorting will place the iPhones off-screen. That's a side issue, though, so I'll merge this now.

**Comment by davedelong** [comment]
Perhaps an alternative approach would be a "document-based" model, where you "open" a particular simulator and then have a whole window/tab just for that simulator

**Comment by twostraws** [comment]
Or we could add toggling buttons below the list to let folks filter what's in there. I'm keen to keep it easy for folks to move between simulators, and having the shoebox approach works well for that.

**Comment by davedelong** [comment]
I had the same idea with the filtering, like in Xcode's project navigator. I'm working on that 👍

**Pull request merged**
