### PR TITLE
Location simulation working on Default simulator

### LINKED ISSUE #46: Location simulation doesn't work on Default simulator
The `Default` simulator has some issues with Location simulation (the tab with the map). 
The hack we're using to toggle current user's simulated position is based on simulator's `udid` property, which is `booted` for the Default one.  

We can work around this by checking if selected simulator's id is `booted` and then broadcast the location notification to all booted devices.

I'll try to put together a PR

note: related to #43 .

### PR DESCRIPTION
**Pull request by stefanomondino**
fixes #46 

Unfortunately, I had to bring down the SimulatorsController to the LocationView to obtain a list of active simulators and broadcast the coordinates notification to all of them.

### CODE REVIEW

**Comment by davedelong** [comment]
I wonder if we should make the `SimulatorsController` be an `EnvironmentObject` 🤔

**Comment by stefanomondino** [comment]
@davedelong nice call! I still don't fully get how Environment Objects are supposed to work, this helped me understand it better!

**Comment by twostraws** [comment]
Is this ready to merge?

**Comment by stefanomondino** [comment]
@twostraws it is now. I've reverted back the declaration of `SimulatorsController` from Env object to `ObservedObject` to avoid lots of conflicts with other commits.
I think that @davedelong suggestion was good but is really hard to implement in a specific pull request like this.

**Pull request merged**
