### PR TITLE
Remove clipped SideBar-Icons

### PR DESCRIPTION
**Pull request by tomminges**
Improve the Sidebar and remove the clipped icons. 

https://github.com/twostraws/ControlRoom/issues/87

First Github PR. Hoply without mistakes :)

### CODE REVIEW

**Comment by twostraws** [comment]
Thank you! This looks great 👍 

I've been wondering about just including the icons directly with the project – it would allow us to ensure they are always there and are a fixed size, and would avoid the problem some folks have seen where their system can't find the icons. Reckon that's possible?

**Comment by tomminges** [comment]
Maybe it´s better. But i think the Icon is bit to height for the small cell. It can produce the same error of course.

**Comment by twostraws** [comment]
Sorry, I meant to do that *as well as* your change, not in place of it 😀

**Comment by tomminges** [comment]
Oh, misunderstood :)

**Pull request merged**
