### PR TITLE
Replace bundle id textfield with a picker

### PR DESCRIPTION
**Pull request by MarioIannotta**
This PR replace the TextField where the user needs to type the bundle identifier with a Picker (aka pull down button)

Final result:
Screen Shot 2020-02-14 at 18 55 33

### CODE REVIEW

**Comment by twostraws** [comment]
This is a really nice improvement – thank you! Is there an advantage to scanning property lists rather than running something like `xcrun simctl listapps booted -j`?

**Comment by MarioIannotta** [comment]
The problem with that command is that it doesn’t provide a json (at least on my machine). It looks like a print of an NSObject. Does it work for you?
I agree it would be a better solution.

**Comment by twostraws** [comment]
Ah, yes – that's not terribly helpful! Perhaps a regex to pull out `CFBundleIdentifier` from that output? (That might be just as flaky as scanning for plist files by hand!)

**Comment by davedelong** [comment]
`xcrun simctl listapps booted -j` produces JSON on my machine... 🤔

**Comment by manojmahapatra** [comment]
`xcrun simctl listapps booted -j` definitely produces a JSON. can confirm.

**Comment by twostraws** [comment]
It's definitely *not* JSON here, so something is up – which is perhaps why it's not documented 😅

**Comment by twostraws** [comment]
This gets me JSON: `xcrun simctl listapps booted -j | plutil -convert json - -o -`

**Comment by MarioIannotta** [comment]
Well that's odd 🤔
here's my log 
[log.txt](https://github.com/twostraws/ControlRoom/files/4206262/log.txt)

**Comment by twostraws** [comment]
@MarioIannotta Yes, that's the format I get too.

**Comment by MarioIannotta** [comment]
Mh, but using `plutil -convert` will fail on @davedelong and @manojmahapatra machines.

**Comment by davedelong** [comment]
Ah, you are correct! I was seeing the structure and assuming it's json. It's definitely not.

This can converted in memory using `PropertyListSerialization`

**Comment by twostraws** [comment]
@davedelong Yeah, that's exactly what my brain did too 😅

**Comment by twostraws** [comment]
OK, so do we have a way forward with that command, @MarioIannotta?

**Comment by MarioIannotta** [comment]
Yep, when Apple will properly support the option `-j` we'll just drop `plutil -convert ...`
I'll update the PR later/tomorrow.

**Comment by twostraws** [comment]
I think Dave was suggesting to decode it directly with https://developer.apple.com/documentation/foundation/propertylistdecoder – it might work, but I don't recall whether that parses property list XML or the string output of such.

**Comment by manojmahapatra** [comment]
ah right, sorry about the false alarm earlier. Did a quick JSON linting and `xcrun simctl listapps booted -j | plutil -convert json - -o -` produces a valid JSON as @twostraws called out.

**Comment by davedelong** [comment]
A bit of digging into `plutil` shows that it's also just using `PropertyListSerialization` and `JSONSerialization` to parse and convert, respectively. That means we can just run `xcrun simctl list apps <udid>`, and then handle the resulting data in-app directly.

**Comment by MarioIannotta** [comment]
PR Updated. I also added a toggle to show/hide system applications from the list.

**Pull request merged**
