### PR TITLE
Install root cert

### PR DESCRIPTION
**Pull request by drmarkpowell**
Hi @twostraws!

I hope this PR finds you healthy and productive and brightens your day a little :)

I needed to add an action to install a trusted root certificate to a simulator, so I followed your lead and added it to Control Room. I find myself needing to use this frequently for my own work now so I reckon there may be a few others out there who'd appreciate having it as well.

Let me know if there is anything I might do to improve this PR once you have a moment to look it over.

### CODE REVIEW

**Comment by twostraws** [comment]
Hello! Sorry it took me a while to get around to this. What does the pbxproj change really do? Is it absolutely needed, and doesn't cause any side effects on Intel?

**Comment by drmarkpowell** [comment]
Hi Paul, no worries.
This change is needed to update PATH to find SwiftLint on M1 Mac homebrew installs. FWIW, the project build still runs fine on Intel...I happen to have one of each Mac right now and I tested it on both. Without the change, everything else is fine but SwiftLint will not be run on M1. Apparently the /opt/homebrew/bin PATH is specialized on the homebrew M1 installation.

references: 
https://stackoverflow.com/questions/65991508/swiftlint-cant-be-found-on-apple-silicon-xcode
and
https://www.anotheriosdevblog.com/installing-swiftlint-on-a-m1/

If for any reason you're not comfortable taking the change I'll be happy to back it out. Your app, your rules :)

**Comment by twostraws** [comment]
I'm finally getting around to reading the blogs you linked to, and it all looks to be in order. Could you resolve the conflicts so I can merge it in? Thank you!

**Comment by drmarkpowell** [comment]
Merge mischief managed.

**Comment by twostraws** [comment]
Marvelous! 🙂

**Pull request merged**
